# Generated by Django 4.2.7 on 2023-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='CategoryImg'),
        ),
    ]
