# Generated by Django 4.2.7 on 2023-11-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_category_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_category',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
