# Generated by Django 4.2.7 on 2023-11-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mainImg',
            field=models.ImageField(blank=True, null=True, upload_to='BlogImg'),
        ),
    ]
