# Generated by Django 4.2.7 on 2023-11-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_mainimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='bio',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='gender',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(blank=True, default=67),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.CharField(default='test@test.com', max_length=50),
            preserve_default=False,
        ),
    ]
