# Generated by Django 4.2.7 on 2023-11-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_caption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
