# Generated by Django 4.2.7 on 2023-11-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_short_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_caption',
            field=models.TextField(blank=True),
        ),
    ]
