# Generated by Django 3.2.9 on 2023-11-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_short_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='This is my Blog', max_length=250),
            preserve_default=False,
        ),
    ]
